organizations:
  apidev-apigeex-sandbox-d29a:
    projects:
      apidev-apigeex-sandbox-d29a:
        environments:
          default:
            status: deploy
kvms: []
targetServers:
  - Netcracker
  - OCS
  - RMCA
sharedflows:
  - auth-northbound-integration
  - auth-southbound
  - rest-cloud-logging
integrations: []
