---
"$schema": https://json-schema.org/draft/2020-12/schema
"$id": https://example.com/product.schema.json
title: Build KVM yaml file
description: Build KVM yaml file
type: object
additionalProperties: false
properties:
  status:
    type: string
    description: Action to execute
    enum:
    - enable
    - disable
  settings:
    type: object
    description: Placeholder for KVM settings.
    additionalProperties: false
    properties:
      scope:
        type: string
        description: Scope of the file.
        enum:
        - org
        - project
      organizations:
        type: object
        description: Organization gcp scope.
        additionalProperties: false
        minProperties: 1
        patternProperties:
          "^[a-zA-Z0-9-_]+$":
            type: object
            description: Project in which the KVM will exist.
            additionalProperties: false
            properties:
              environments:
                type: object
                description: Environments placeholder.
                minProperties: 1
                additionalProperties: false
                patternProperties:
                  "^[a-zA-Z0-9-_]+$":
                    type: object
                    description: Environment data of the KVM.
                    additionalProperties: false
                    properties:
                      data:
                        "$ref": "#/$defs/commonData"
                    required:
                    - data
            required:
            - environments
    required:
    - scope
    - organizations
required:
- status
- settings
"$defs":
  commonData:
    anyOf:
      - type: string
      - type: object
        additionalProperties: false
        properties:
          name:
            type: string
          encrypted:
            type: boolean
          keyValueEntries:
            type: array
            items:
              type: object
              additionalProperties: false
              properties:
                name:
                  type: string
                value:
                  type: string
              required:
              - name
              - value
          nextPageToken:
            type: string
        required:
        - name
        - encrypted
        - keyValueEntries
