name: 'APIGEE OPS [Publish Docker Image]'
on:
  workflow_dispatch:
env:
  IMAGE_NAME: apigee-ops-sub-folder
#
jobs:
  # This pushes the image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file contrib/cliOPS/_contrib/github/Dockerfile --tag $IMAGE_NAME

      - name: Log in to registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u pedro-andre-dias-alb --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # This changes all uppercase characters to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # This strips the git ref prefix from the version.
          VERSION=$(echo "1.1.0" | sed -e 's,.*/\(.*\),\1,')
          #tag name.
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION