name: '[ APIGEE ] Proxy Linter PR dev-main'
on:
  pull_request:
    branches:
      - dev-main
    paths:
      - 'src/main/apigee/apiproxies/**'

jobs:
  updatesGet:
    runs-on: ubuntu-latest
    outputs:
      PROXY_LIST: ${{ steps.proxyGet.outputs.proxies }}

    steps:
      - uses: actions/checkout@v3

      - id: proxyUpdated
        name: Get proxy name with changes to deploy        
        uses: tj-actions/changed-files@v37
        with:
          dir_names: true
          dir_names_max_depth: 5
          files: |
            src/main/apigee/apiproxies/**

      - id: proxyGet
        name: Get the current proxy change
        run: |
          proxyList=""
          for proxy in ${{ steps.proxyUpdated.outputs.all_modified_files }}; do              
              [ ! -z "$proxyList" ] && proxyList+=","
              proxyList+="'$(basename $proxy)'"
          done
        
          echo "$proxyList"
          echo "proxies=[$proxyList]" >> $GITHUB_OUTPUT

  proxies-preCheck:
    needs: updatesGet
    environment: DEVCI
    runs-on: ubuntu-latest    
    if: ${{ needs.updatesGet.outputs.PROXY_LIST != '[]' }}
    strategy:
        max-parallel: 5
        matrix:
            PROXY_NAME: ${{ fromJSON(needs.updatesGet.outputs.PROXY_LIST) }}
    env:
      COMPONENT_PATH: ${{ format('{0}/apiproxies/{1}/apiproxy/', 'src/apigee' , matrix.PROXY_NAME) }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install apigeelint
        run: |
          npm install -g apigeelint
          
      - name: Run apigee linter
        continue-on-error: true
        run: |          
          apigeelint -s ${{env.COMPONENT_PATH}} -f table.js --profile apigeex

        