name: "Push to another repo"
on:
  workflow_dispatch:
jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "goncalo.freitas.vilela@devoteam.com"
          git config --global user.name "gvilela7"
          git checkout -b new-branch
          git remote add destination_repository https://github.com/gvilela7/dryrun_vilela.git

      - name: Create a new text file
        run: echo "Hello, this is a new text file." > newfile.txt

      - name: Set remote URL and push code
        run: |
          git remote set-url destination_repository "https://${DESTINATION_REPO_TOKEN}@github.com/gvilela7/dryrun_vilela.git"
          git add newfile.txt
          git commit -m "Automated commit from GitHub Actions"
          git push destination_repository new-branch
