name: Create Branch in Target Repository

on:
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt-get update
        sudo apt-get install gh

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Create branch in target repository
      env:
        TARGET_REPO_USERNAME: gvilela7
        TARGET_REPO_NAME: dryrun_vilela
      run: |
        # Authenticate with GitHub CLI using the token
        gh auth login --with-token <<< "${{ secrets.TARGET_REPO_TOKEN }}"

        # Create a new branch in the target repository
        gh repo create $TARGET_REPO_USERNAME/$TARGET_REPO_NAME -p
        git push origin HEAD:new_branch_name || echo "Failed to push branch to target repository"

        # Show remotes for debugging
        git remote -v