name: Create Branch in Target Repository
on:
  workflow_dispatch:
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PIPELINE_ACCESS }}
          repository: gvilela7/dryrun_vilela
          ref: ${{ github.ref_name }}
          sparse-checkout: |
            text.txt
            naoMexe.txt
          path: tmp
      - name: Edit Files
        id: modifiedFiles 
        run: |
          cd tmp
          cat text.txt
          echo "hello world" >> text.txt
          echo "second print:"
          cat naoMexe.txt
          cat text.txt
          echo "ficheiros alterados: $(git ls-files -o -m)"
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$(git ls-files -o -m --exclude-standard -- ':!:contrib/*' ':!node_modules/*' | tr '\n' ' ')" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Commit Files
        if: ${{ steps.modifiedFiles.outputs.result != '' }}        
        run: |
          cat tmp/text.txt
          echo "modified files: ${{steps.modifiedFiles.outputs.result}}"
          echo "repo name: ${{github.event.repository.name}}"
          echo "ref name: $GITHUB_REF_NAME"
          echo "ref name:: ${{ github.ref_name }}"
          npm install axios
          
          node .github/GitVerifiedCommit/index.js \
               ${{secrets.PIPELINE_ACCESS}} \
               $GITHUB_REPOSITORY_OWNER \
               dryrun_vilela \
               $GITHUB_REF_NAME \
               "${{steps.modifiedFiles.outputs.result}}" \
               '[AUTO] Committing files updated by imports'

      - name: Clean repo sync              
        run: |
          sudo rm -rf tmp 