name: "Push to another repo"
on: [workflow_dispatch]
jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "goncalo.freitas.vilela@devoteam.com"
          git config --global user.name "gvilela7"

      - name: Create a new text file
        run: echo "Hello, this is a new text file." > newfile.txt

      - name: Create and switch to a new branch
        run: |
          git remote add destination_repo https://github.com/gvilela7/dryrun_vilela.git
          git checkout -b new-feature-branch

      - name: Add, commit, and push code
        run: |
          git add newfile.txt
          git commit -m "Automated commit from GitHb Actions"
          echo $(git remote get-url destination_repo)
          git push https://$DESTINATION_REPO_TOKEN@github.com/gvilela7/dryrun_vilela.git new-feature-branch