name: Create Branch in Target Repository

on:
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PIPELINE_ACCESS }}
          repository: gvilela7/dryrun_vilela
          ref: ${{ github.ref_name }}
          sparse-checkout: |
            text.txt
            naoMexe.txt
          path: tmp

      - name: Edit Files 
        run: |
          cd tmp
          echo "hello world" >> text.txt
          cat naoMexe.txt
          cat text.txt
          echo "ficheiros alterados: $(git ls-files -o -m)"
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$(git ls-files -o -m --exclude-standard -- ':!:contrib/*' ':!node_modules/*' | tr '\n' ' ')" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "${{steps.modifiedFiles.outputs.result}}"

      - name: Commit Files
        if: ${{ steps.modifiedFiles.outputs.result != '' }}        
        run: |
          echo "${{steps.modifiedFiles.outputs.result}}"
       ##   npm install axios
          
       #   node .github/GitVerifiedCommit/index.js \
       #         ${{secrets.PIPELINE_ACCESS}} \
       #         gvilela7 \
       #         dryrun_vilela \
       #         ${{ github.ref_name }} \
       #         "${{steps.modifiedFiles.outputs.result}}" \
       #         '[AUTO] Committing files updated by imports'                   

