name: "Push to another repo"
on:
  workflow_dispatch:
jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "goncalo.freitas.vilela@devoteam.com"
          git config --global user.name "gvilela7"
          git remote add destination_repository https://github.com/gvilela7/dryrun_vilela.git
          git checkout -b new-branch
          git config --local credential.helper "!f() { echo username=oauth; echo password=${DESTINATION_REPO_TOKEN}; }; f"
          
      - name: Create a new text file
        run: echo "Hello, this is a new text file." > newfile.txt

      - name: Add, commit, and push code
        run: |
          git add newfile.txt
          git commit -m "Automated commit from GitHub Actions"
          git push destination_repository new-branch
